# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2017-04-19')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('release', models.DateField()),
                ('banner', models.CharField(default='/static/jtc/img/name.jpg', max_length=200)),
                ('menu_poster', models.CharField(default='/static/jtc/img/name.jpg', max_length=200)),
                ('poster', models.CharField(default='/static/jtc/img/name.jpg', max_length=200)),
                ('page_link', models.TextField(blank=True, null=True)),
                ('trailer_link', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('story_line', models.TextField()),
                ('genre', models.ManyToManyField(to='jtc.Genre')),
            ],
            options={
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=200)),
                ('seats_avail', models.BooleanField(default=True)),
                ('date', models.ManyToManyField(to='jtc.Date')),
            ],
            options={
                'verbose_name_plural': 'multiplexes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('movie', models.CharField(default='movie_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.CharField(default='/static/jtc/img/name.jpg', max_length=100)),
                ('gender', models.CharField(default='Actor', max_length=7)),
                ('about', models.TextField(default='A very talented acter')),
                ('roles', models.ManyToManyField(to='jtc.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TimeField(default='09:50:00')),
            ],
        ),
        migrations.CreateModel(
            name='UMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='fname', max_length=15)),
                ('lname', models.CharField(default='lname', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='star',
            name='upcoming_movies',
            field=models.ManyToManyField(to='jtc.UMovie'),
        ),
        migrations.AddField(
            model_name='multiplex',
            name='time',
            field=models.ManyToManyField(to='jtc.Time'),
        ),
        migrations.AddField(
            model_name='movies',
            name='multiplexes',
            field=models.ManyToManyField(to='jtc.Multiplex'),
        ),
        migrations.AddField(
            model_name='movies',
            name='stars',
            field=models.ManyToManyField(to='jtc.Star'),
        ),
    ]
