# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jtc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jtc.Date')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jtc.Movies')),
                ('multiplex_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jtc.Multiplex')),
            ],
            options={
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Snumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_avail', models.BooleanField(default=True)),
                ('seat_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='snumber',
            unique_together=set([('seat_avail', 'seat_name')]),
        ),
        migrations.AddField(
            model_name='seats',
            name='seat_no',
            field=models.ManyToManyField(to='jtc.Snumber'),
        ),
        migrations.AddField(
            model_name='seats',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jtc.Time'),
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together=set([('movie_name', 'multiplex_name', 'date', 'time')]),
        ),
    ]
