# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtc', '0002_auto_20170423_2113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiplex',
            unique_together=set([('name', 'location')]),
        ),
    ]
