# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtc', '0003_auto_20170430_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snumber',
            options={'ordering': ['id']},
        ),
    ]
