# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jtc', '0005_auto_20170501_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplex',
            name='movie',
            field=models.CharField(default='movie', max_length=30),
        ),
    ]
