# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtc', '0006_multiplex_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplex',
            options={'ordering': ['movie'], 'verbose_name_plural': 'multiplexes'},
        ),
    ]
